added rs 3rd party
lsd-maddrive/maddrive_ros_shared pull request #1
Opened 2022-11-09 12:10 UTC by lasauveetgarde

Added realsense-ros package to 3rd party install

2022-11-09 19:48 UTC, KaiL4eK commented on scripts/install_third_party.sh
> +sudo apt purge ros-$ROS_DISTRO-librealsense2
не, такое делать не надо
если человек ставит из apt, то это решение)
надо команды apt убрать

2022-11-09 19:48 UTC, KaiL4eK requested changes
Убрать команды apt из скрипта установки

2022-11-09 21:38 UTC, Alakeyska commented on scripts/install_third_party.sh
> +sudo apt purge ros-$ROS_DISTRO-librealsense2
Для сборки написанно нужен rosdep. Как иначе указать, что его нужно поставить? Это всё из инструкции Intel.

2022-11-11 16:56 UTC, KaiL4eK requested changes
Убрать rosdep, остальное ок

2022-11-11 16:56 UTC, KaiL4eK commented on scripts/install_packages.sh
> +sudo apt install python3-rosdep
Все относительно rosdep убрать, это видится лишним

2022-11-11 16:56 UTC, KaiL4eK commented on scripts/install_packages.sh
> +sudo apt purge ros-$ROS_DISTRO-librealsense2
Оставить, для описания желаемого состояния системы

2022-11-18 09:39 UTC, Alakeyska commented on scripts/install_packages.sh
> +sudo apt purge ros-$ROS_DISTRO-librealsense2
Сделано

2022-11-29 06:46 UTC, merged